services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: homi_shoppi_react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/app/public  
      - ./frontend/src:/app/src
    command: ["npm", "start"]
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: homi_shoppi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homi_shoppi_db
      MYSQL_USER: user 
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  
  
  microservice-product:
    build: 
      context: ./backend/product-service
      dockerfile: Dockerfile
    container_name: microservice-product
    ports:
      - "5001:5000"
    depends_on:
      - database

  server:
    image: nginx
    container_name: homi_shoppi_nginx
    volumes:
      - ./server/templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=user
      - NGINX_PORT=80
    

volumes:
  db_data: