networks:
  hs-network:
    driver: bridge

services:
  hs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/app/public  
      - ./frontend/src:/app/src
    command: ["npm", "start"]
    networks:
      - hs-network
  
  hsdb:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: hsdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hsdb
      MYSQL_USER: user 
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - hs-network

  microservice-order:
    build: 
      context: ./backend/order-service
      dockerfile: Dockerfile
    container_name: microservice-order
    ports:
      - "5003:5003"
    depends_on:
      - hsdb
    networks:
      - hs-network    
  
  microservice-product:
    build: 
      context: ./backend/product-service
      dockerfile: Dockerfile
    container_name: microservice-product
    ports:
      - "5004:5004"
    depends_on:
      - hsdb
    networks:
      - hs-network 

  microservice-shop-cart:
    build: 
      context: ./backend/shop-cart-service
      dockerfile: Dockerfile
    container_name: microservice-shop-cart
    ports:
      - "5005:5005"
    depends_on:
      - hsdb
    networks:
      - hs-network  

  microservice-user:
    build: 
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: microservice-user
    ports:
      - "5006:5006"
    depends_on:
      - hsdb
    networks:
      - hs-network   

  hs-nginx:
    image: nginx
    container_name: hs-nginx
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=user
      - NGINX_PORT=80
    networks:
      - hs-network  
    