apiVersion: v1
data:
  App.js: "import {BrowserRouter, Routes, Route} from \"react-router-dom\"\nimport NavBar from './components/Navbar/Navbar.js';\nimport Home from './pages/Home/Home.js';\nimport Account from './pages/Account/Account.js';\nimport ShopCart from './pages/ShopCart/ShopCart.js';\nimport Product from './pages/Product/Product.js';\nimport Register from './pages/Register/Register.js';\nimport Login from './pages/Login/Login.js';\nimport { GetShopCarts } from './hooks/shop-cart-hook.js';\n\nfunction App() {\n  const {data: shopCarts } = GetShopCarts();\n\n  const cookies = document.cookie.split('; ').reduce((acc, cookie) => {\n    const [name, value] = cookie.split('=');\n    acc[name] = value;\n    return acc;\n  }, {});\n\n  var foundShopCart = null;\n  if(cookies != null && shopCarts != null) {\n    foundShopCart = shopCarts.find((shopCart) => parseInt(shopCart.UserID) === parseInt(cookies.loggedUser));\n  } \n\n  if (foundShopCart) {\n    sessionStorage.setItem('currentShopCartID', foundShopCart.ShopCartID);\n  } \n\n  return ( \n    <BrowserRouter>\n      <NavBar/>\n      <Routes>\n        <Route path=\"/\" element={<Home/>}/>\n        <Route path=\"account/:id\" element={<Account/>}/>\n        {cookies.loggedUser && foundShopCart ? (\n          <Route\n            path={`shopcart/${foundShopCart.ShopCartID}`}\n            element={<ShopCart shopCartId={foundShopCart.ShopCartID} />}\n          />\n        ) : (\n          <Route path=\"/shopcart\" element={<Login />} />\n        )}\n        <Route path=\"/product/:id\" element={<Product/>}/>\n        <Route path=\"/login\" element={<Login/>}/>\n        <Route path=\"/register\" element={<Register/>}/>\n      </Routes>\n    </BrowserRouter>\n  );\n}\n\nexport default App;"
  App.test.js: |
    import { render, screen } from '@testing-library/react';
    import App from './App';

    test('renders learn react link', () => {
      render(<App />);
      const linkElement = screen.getByText(/learn react/i);
      expect(linkElement).toBeInTheDocument();
    });
  index.js: |
    import React from 'react';
    import ReactDOM from 'react-dom/client';
    import 'bootstrap/dist/css/bootstrap.min.css';
    import App from './App';
    //import reportWebVitals from './reportWebVitals';

    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(
      <React.StrictMode>
        <App />
      </React.StrictMode>
    );

    // If you want to start measuring performance in your app, pass a function
    // to log results (for example: reportWebVitals(console.log))
    // or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
    //reportWebVitals();
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: hs-frontend
  name: hs-frontend-cm1
