apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: hs-frontend
  name: hs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hs-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: hs-frontend
    spec:
      containers:
        - args:
            - npm
            - start
          image: hs-frontend
          name: hs-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/public
              name: hs-frontend-cm0
            - mountPath: /app/src
              name: hs-frontend-cm1
      restartPolicy: Always
      volumes:
        - configMap:
            name: hs-frontend-cm0
          name: hs-frontend-cm0
        - configMap:
            name: hs-frontend-cm1
          name: hs-frontend-cm1
