apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: hs-nginx
  name: hs-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hs-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: hs-nginx
    spec:
      containers:
        - env:
            - name: NGINX_HOST
              value: user
            - name: NGINX_PORT
              value: "80"
          image: nginx
          name: hs-nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: hs-nginx-cm0
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: hs-nginx-cm0
          name: hs-nginx-cm0
