apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cloudcomputing-hsdb
  name: cloudcomputing-hsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudcomputing-hsdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cloudcomputing-hsdb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: hsdb
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_USER
              value: user
          image: cloudcomputing-hsdb
          imagePullPolicy: Never
          name: cloudcomputing-hsdb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: cloudcomputing-hsdb-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: cloudcomputing-hsdb-cm0
          name: cloudcomputing-hsdb-cm0
