apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: microservice-order
  name: microservice-order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice-order
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: microservice-order
    spec:
      containers:
        - image: microservice-order
          name: microservice-order
          ports:
            - containerPort: 5003
              protocol: TCP
      restartPolicy: Always
