apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cloudcomputing-microservice-product
  name: cloudcomputing-microservice-product
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudcomputing-microservice-product
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cloudcomputing-microservice-product
    spec:
      containers:
        - image: cloudcomputing-microservice-product
          name: cloudcomputing-microservice-product
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
              protocol: TCP
      restartPolicy: Always
