apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cloudcomputing-microservice-shop-cart
  name: cloudcomputing-microservice-shop-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudcomputing-microservice-shop-cart
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cloudcomputing-microservice-shop-cart
    spec:
      containers:
        - image: cloudcomputing-microservice-shop-cart
          name: cloudcomputing-microservice-shop-cart
          imagePullPolicy: Never
          ports:
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
