apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: microservice-shop-cart
  name: microservice-shop-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice-shop-cart
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: microservice-shop-cart
    spec:
      containers:
        - image: microservice-shop-cart
          name: microservice-shop-cart
          ports:
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
